M48
; DRILL file {KiCad 7.0.8} date 2024 April 10, Wednesday 13:39:45
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-10T13:39:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.1339Y-4.4567
X5.252Y-4.4567
T2
X5.0787Y-4.1161
X5.9685Y-4.1161
T0
M30
